export default {
  size: {
    title: '尺寸',
    type: String,
    default: 'lg',
    hiddenInEdit: true,
  },
  couponAmount:{
    title:'优惠券',
    type:String,
    default:'',
    hiddenInEdit: true,
  },
  h5Url: {
    title: '商品ID',
    type: String,
    default: '',
  },
  productId: {
    type: [Number, String],
    default: null,
    hiddenInEdit: true,
  },
  channelCode: {
    title: '商品来源',
    type: [Number, String],
    default: '0',
    options: [
      { title: '淘宝', value: '10' },
      { title: '天猫', value: '11' },
      { title: '京东', value: '2' },
      { title: '拼多多', value: '3' },
      { title: '唯品会', value: '4' },
      { title: '苏宁', value: '5' },
    ],
  },
  subChannelCode:{
    title:'商品子来源',
    type: [Number, String],
    default: null,
    hiddenInEdit: true,
  },
  corner: {
    title: 'Logo',
    type: String,
    default: '',
  },
  discountIcon: {
    title: '优惠信息标',
    type: String,
    default: '',
    hiddenInEdit: true,
  },
  tips: {
    title: '营销标',
    type: String,
    default: '',
  },
  tipsSize: {
    title: '营销标大小',
    type: Number,
    default: 25,
    inputNumber: { min: 0 },
  },
  tipsColor: {
    title: '营销标背景色',
    type: String,
    default: '#00abff',
  },
  masterImg: {
    title: '头图',
    type: String,
    default:
      'http://wiki.weilaijishi.cn/uploads/images/gallery/2019-09/image-1568704343559.png',
  },
  prefixIcon: {
    title: '标题活动标',
    type: String,
    default:
      '//lego-activity-dev.weilaijishi.com/resource/1b5d7200-ec92-11e9-b458-e19b461cfb72',
  },
  prefixIconSize: {
    title: '标题活动标大小',
    type: Number,
    default: 14,
    inputNumber: { min: 0 },
    hiddenInEdit: true,
  },
  switchTitleSubtitle: {
    title: '标题利益点互换',
    type: Boolean,
    checkBox: true,
    default: false,
    hiddenInEdit: true,
  },
  subTitle: {
    title: '副标题',
    type: String,
    default: '',
  },
  subtitleFontSize: {
    title: '利益点字号',
    type: Number,
    default: 14,
    inputNumber: { min: 0 },
    hiddenInEdit: true,
  },
  subtitleColor: {
    title: '利益点颜色',
    type: String,
    default: '#8c8c8c',
    hiddenInEdit: true,
  },
  priceLayout: {
    title: '价格位置',
    type: [String, Number],
    default: 1,
    hiddenInEdit: true,
  },
  titleLayout: {
    title: '标题布局',
    type: [String, Number],
    default: 1,
    hiddenInEdit: true,
  },
  name: {
    title: '标题',
    type: String,
    default: '我是商品标题我是商品我是商品标题我是商品',
  },
  titleFontSize: {
    title: '标题字号',
    type: Number,
    default: 14,
    inputNumber: { min: 0 },
    hiddenInEdit: true,
  },
  titleColor: {
    title: '标题颜色',
    type: String,
    default: '#000',
    hiddenInEdit: true,
  },
  actPrice: {
    title: '活动价',
    type: [Number, String],
    default: '',
    hiddenInEdit: true,
  },
  price: {
    title: '价格',
    type: [Number, String],
    default: '',
  },
  salePricePrefix: {
    title: '销售价前缀',
    type: String,
    default: '',
    hiddenInEdit: true,
  },
  marketPrice: {
    title: '市场价',
    type: [Number, String],
    default: '',
  },
  seckillPrice: {
    title: '秒杀价',
    type: [Number, String],
    default: '',
  },
  isHighCommission: {
    title: '高佣商品',
    type: Boolean,
    default: false,
    checkBox: true,
    hiddenInEdit: true,
  },
  isSpike: {
    title: '秒杀模块',
    type: Boolean,
    default: false,
    checkBox: true,
    hiddenInEdit: true,
  },
  isFight: {
    title: '拼团模块',
    type: Boolean,
    default: false,
    checkBox: true,
    hiddenInEdit: true,
  },
  commission: {
    title: '佣金',
    type: [Number, String],
    default: '',
  },
  btnText: {
    title: '按钮文案',
    type: String,
    default: '',
  },
  btnColor: {
    title: '按钮背景色',
    type: String,
    default: '',
    hiddenInEdit: true,
  },
  sales: {
    title: '已拼数',
    type: [Number, String],
    default: 0,
    hiddenInEdit: true,
  },
  limitTuanCount: {
    title: '限制成团数',
    type: [Number, String],
    default: 0,
    hiddenInEdit: true,
  },
  pintuanSuccessCount: {
    title: '已开团数',
    type: [Number, String],
    default: 0,
    hiddenInEdit: true,
  },
  headList: {
    title: '用户头像',
    type: Array,
    default: _ => [
      'http://lego-activity-dev.weilaijishi.com/resource/4322f4d0-0066-11ea-b1d6-d7176f1abd8d.jpg',
    ],
    hiddenInEdit: true,
  },
}
